name: Get latest release branches

inputs:
  current-version:
    required: true

outputs:
  latest:
    value: ${{ fromJson(steps.get-latest-release-branch.outputs.result).latest }}
  secondLatest:
    value: ${{ fromJson(steps.get-latest-release-branch.outputs.result).secondLatest }}
  thirdLatest:
    value: ${{ fromJson(steps.get-latest-release-branch.outputs.result).thirdLatest }}

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      id: get-latest-release-branch
      with:
        result-encoding: string
        script: | # js
          const currentVersion = Number(${{ inputs.current-version }});

          const result =  {
            latest: `release-x.${currentVersion}.x`,
            secondLatest: `release-x.${currentVersion - 1}.x`,
            thirdLatest: `release-x.${currentVersion - 2}.x`,
          };

          console.log(result);

          return result;
