name: Get latest release branch

outputs:
  branch-name:
    value: ${{ parseJson(steps.get-latest-release-branch.outputs.result) }}

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      id: get-latest-release-branch
      with:
        result-encoding: string
        script: | # js
          const currentVersion = Number(${{ vars.CURRENT_VERSION }});

          const result =  {
            latest: `release-x.${currentVersion}.x`,
            secondLatest: `release-x.${currentVersion - 1}.x`,
            thirdLatest: `release-x.${currentVersion - 2}.x`,
          };

          console.log(result);

          return result;
