name: Auto-backport
on:
  pull_request:
    # types: [closed, labeled] FIXME FOR TESTING

jobs:
  create-backport:
    # if: github.event.pull_request.merged == true && (contains(github.event.pull_request.labels.*.name, 'backport') || contains(github.event.pull_request.labels.*.name, 'double-backport') && github.event.action == 'closed' || github.event.label.name == 'backport' || github.event.label.name == 'double-backport')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.METABASE_AUTOMATION_USER_TOKEN }}
      # - uses: ./.github/actions/find-squashed-commit
      #   name: Find commit
      #   id: find_commit
      #   with:
      #     pull-request-number: ${{ github.event.pull_request.number }}
      #     base-ref: ${{ github.event.pull_request.base.ref }}

      - uses: ./.github/actions/get-latest-release-branch
        name: Get latest release branch
        id: get_latest_release_branch

      # - name: Single Backport
      #   uses: ./.github/actions/create-backport
      #   with:
      #     target-branch: ${{ steps.get_latest_release_branch.outputs.latest-release-branch }}
      #     backport-branch: ${{ steps.find_commit.outputs.commit-sha }}

      # - name: Double Backport
      #   uses: ./.github/actions/create-backport
      #   if: contains(github.event.pull_request.labels.*.name, 'double-backport') || github.event.label.name == 'double-backport'
      #   with:
      #     target-branch: ${{ steps.get_latest_release_branch.outputs.latest-release-branch }}
      #     backport-branch: ${{ steps.find_commit.outputs.commit-sha }}

